import Header from "@/components/layout/navigation/Header";
import "../styles/main.scss";
import Footer from "@/components/layout/navigation/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="relative h-full min-h-screen ">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
