import Header from "@/components/layout/navigation/Header";
import "../styles/main.scss";
import Footer from "@/components/layout/navigation/Footer";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="relative h-full min-h-screen ">
        <ToastContainer />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
