export const colors = [
  { id: 0, value: "Banan", title: "Banan" },
  { id: 1, value: "Barbie", title: "Barbie" },
  { id: 2, value: "Błękitny", title: "Błękitny" },
  { id: 3, value: "Brudny róż", title: "Brudny róż" },
  { id: 4, value: "Brzoskwinia", title: "Brzoskwinia" },
  { id: 5, value: "Ceglany", title: "Ceglany" },
  { id: 6, value: "Chabrowy", title: "Chabrowy" },
  { id: 7, value: "Ciasteczko", title: "Ciasteczko" },
  { id: 8, value: "Ciemnozielony", title: "Ciemnozielony" },
  { id: 9, value: "Cukierkowy", title: "Cukierkowy" },
  { id: 10, value: "Cukierkowy róż", title: "Cukierkowy róż" },
  { id: 11, value: "Cynamon", title: "Cynamon" },
  { id: 12, value: "Cytryna", title: "Cytryna" },
  { id: 13, value: "Czarny", title: "Czarny" },
  { id: 14, value: "Czekolada", title: "Czekolada" },
  { id: 15, value: "Czerwony", title: "Czerwony" },
  { id: 16, value: "Fiołkowy", title: "Fiołkowy" },
  { id: 17, value: "Grafitowy", title: "Grafitowy" },
  { id: 18, value: "Granatowy", title: "Granatowy" },
  { id: 19, value: "Ivory", title: "Ivory" },
  { id: 20, value: "Jagodowy", title: "Jagodowy" },
];
