export const products = [
  {
    id: 1,
    title: "Opaska typ 1",
    category: "opaski",
    price: 15,
    discountPrice: null,
    description:
      "Ręcznie wykonana opaska z przędzy bawełnianej T-shirt yarn typu premium. <br> Szerokość opaski – 3 cm. <br> Wygodna, bez uciskowa. <br> Róźne kolory do wyboru, zdjęcia znajdują się w galerii.",
    isAvailable: true,
    isNew: false,
    isImmediate: true,
  },
  {
    id: 2,
    title: "Opaska 2",
    category: "opaski",
    price: 15,
    discountPrice: null,
    description: "",
    isAvailable: true,
    isNew: false,
    isImmediate: true,
  },
  {
    id: 22,
    title: "Opaska typ 3",
    category: "opaski",
    price: 18,
    discountPrice: null,
    description: "",
    isAvailable: true,
    isNew: false,
    isImmediate: true,
  },
  {
    id: 3,
    title: "Torebka 1",
    category: "plecaki",
    price: 90,
    description: "",
    isAvailable: false,
    isNew: false,
    isImmediate: false,
  },
  {
    id: 4,
    title: "Torebka 2",
    category: "plecaki",
    price: 80,
    discountPrice: null,
    description: "",
    isAvailable: true,
    isNew: true,
    isImmediate: false,
  },
  {
    id: 5,
    title: "Plecak",
    category: "plecaki",
    price: 120,
    discountPrice: 18,
    description: "",
    isAvailable: true,
    isNew: false,
    isImmediate: false,
  },
  {
    id: 6,
    title: "Koszyk z ażurowym wieczkiem",
    category: "koszyki",
    price: 60,
    discountPrice: null,
    description:
      "Ręcznie wykonany koszyk ze sznurka bawełnianego z ażurowym wieczkiem oraz mocnym spodem z drewnianej sklejki. <br> Idealny do przechowywania różnych rzeczy lub na prezent. <br> Średnica koszyka 20 cm.",
    isAvailable: true,
    isNew: false,
    isImmediate: false,
  },
];
